name: Generate Documentation
on: [push, pull_request]

jobs:
  generate_documentation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Node.js Environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Switch to Yarn Berry
        run: yarn set version berry

      - name: Install Dependencies
        run: yarn

      - name: Generate Documentation
        run: yarn docs:generate

      - name: Deploy Documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: docs
